# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Current configuration doesn't require a GitHub token
          token: NOT_NEEDED

          # Options
          user: ravana69
          template: classic
          base: metadata
          config_timezone: Asia/Kolkata
          plugin_screenshot: yes
          plugin_screenshot_background: no
          plugin_screenshot_selector: body
          plugin_screenshot_title: Location
          plugin_screenshot_url: https://www.google.com/maps/@23.2038601,80.0063943,75m/data=!3m1!1e3!5m1!1e4?entry=ttu
